Added Maddy server
Other cleanup along the way

diff --git a/serfs/addsubdomain b/serfs/addsubdomain
--- a/serfs/addsubdomain
+++ b/serfs/addsubdomain
@@ -28,14 +28,14 @@ if [ -e "/opt/verb/mods/addsubdomain.before" ]; then . /opt/verb/mods/addsubdoma
 
 
 # Dependencies
-if ! /bin/grep -q 'InkCertInstalled="DONE"' /opt/verb/conf/inkcertstatus; then
+if ! /usr/bin/grep -q 'InkCertInstalled="DONE"' /opt/verb/conf/inkcertstatus; then
   /usr/bin/echo "Install inkCert first, I quit."; exit 8
 fi
-if ! /bin/grep -q 'InkDNSStat="INSTALLED"' /opt/verb/conf/inkdnsconf; then
+if ! /usr/bin/grep -q 'InkDNSStat="INSTALLED"' /opt/verb/conf/inkdnsconf; then
   /usr/bin/echo "Install inkDNS first, I quit."; exit 8
 fi
-if ! /bin/grep -q 'ServerMailStatus="VMAIL_SERVER"' /opt/verb/conf/servermailpath; then
-  /usr/bin/echo "Install Postfix Vmail first, I quit."; exit 8
+if /usr/bin/grep -q 'EmailAllowed="YES"' /opt/verb/conf/servernameip && ! /usr/bin/grep -q 'ServerMailStatus="VMAIL_SERVER"' /opt/verb/conf/servermailpath && ! /usr/bin/grep -q 'ServerMailStatus="MADDY_EMAIL_SERVER"' /opt/verb/conf/servermailpath; then
+  /usr/bin/echo "Install either Maddy Email or Postfix Vmail first, I quit."; exit 8
 fi
 
 # Include the config
@@ -47,17 +47,17 @@ olddomain=$2
 # Check if it already exists
 if [ -f /opt/verb/conf/webserver/sites-available/httpd/${subdomain}.${olddomain}.conf ]; then
  if [ -f /etc/httpd/sites-enabled/${subdomain}.${olddomain}.conf ]; then
-   /bin/echo "That subdomain already exists."
+   /usr/bin/echo "That subdomain already exists."
    exit 7
  else
-   /bin/echo "That site's config exists, but it doesn't seem to be active on Apache. Something's not right."
+   /usr/bin/echo "That site's config exists, but it doesn't seem to be active on Apache. Something's not right."
    exit 8
  fi
 fi
 
 # Check the domain shell
 if [ ! -f /opt/verb/conf/inkcert/cli-ini/siteinkcert.${olddomain} ]; then
-  /bin/echo "The shell for ${olddomain} does not exist yet. Creating it..."
+  /usr/bin/echo "The shell for ${olddomain} does not exist yet. Creating it..."
   /opt/verb/serfs/newdomainshell ${olddomain}
   wait
 fi
@@ -65,16 +65,16 @@ fi
 # Server config files
 ## Web directory
 if [ ! -d /srv/www/domains/${subdomain}.${olddomain} ]; then
-  /bin/cp -rf /opt/verb/conf/site-files/newdomain.tld /srv/www/domains/${subdomain}.${olddomain}
+  /usr/bin/cp -rf /opt/verb/conf/site-files/newdomain.tld /srv/www/domains/${subdomain}.${olddomain}
 fi
-  /bin/ln -sfn /srv/www/domains/${subdomain}.${olddomain} /srv/www/html/
-  /bin/chown -R www:www /srv/www/html/${subdomain}.${olddomain}
-  /bin/chown -R www:www /srv/www/domains/${subdomain}.${olddomain}
-  /bin/chmod -R 750 /srv/www/domains/${subdomain}.${olddomain}
+  /usr/bin/ln -sfn /srv/www/domains/${subdomain}.${olddomain} /srv/www/html/
+  /usr/bin/chown -R www:www /srv/www/html/${subdomain}.${olddomain}
+  /usr/bin/chown -R www:www /srv/www/domains/${subdomain}.${olddomain}
+  /usr/bin/chmod -R 750 /srv/www/domains/${subdomain}.${olddomain}
 ## Copy
 if [ ${ServerType} = "lemp" ]; then
   /usr/bin/cp /opt/verb/conf/site-files/conf/newnginxdomain.tld.conf /opt/verb/conf/webserver/sites-available/nginx/${subdomain}.${olddomain}.conf
-  /bin/sed -i "s/newdomain.tld/${subdomain}.${olddomain}/g" /opt/verb/conf/webserver/sites-available/nginx/${subdomain}.${olddomain}.conf
+  /usr/bin/sed -i "s/newdomain.tld/${subdomain}.${olddomain}/g" /opt/verb/conf/webserver/sites-available/nginx/${subdomain}.${olddomain}.conf
   ## Server
   /opt/verb/serfs/ensitenginx -r ${subdomain}.${olddomain}
 elif [ ${ServerType} = "lamp" ]; then
@@ -85,8 +85,8 @@ elif [ ${ServerType} = "lamp" ]; then
 elif [ ${ServerType} = "laemp" ]; then
   /usr/bin/cp /opt/verb/conf/site-files/conf/newdomain.tld.conf /opt/verb/conf/webserver/sites-available/httpd/${subdomain}.${olddomain}.conf
   /usr/bin/cp /opt/verb/conf/site-files/conf/newrpnginxdomainhttp.tld.conf /opt/verb/conf/webserver/sites-available/nginx/${subdomain}.${olddomain}.conf
-  /bin/sed -i "s/newdomain.tld/${subdomain}.${olddomain}/g" /opt/verb/conf/webserver/sites-available/httpd/${subdomain}.${olddomain}.conf
-  /bin/sed -i "s/newdomain.tld/${subdomain}.${olddomain}/g" /opt/verb/conf/webserver/sites-available/nginx/${subdomain}.${olddomain}.conf
+  /usr/bin/sed -i "s/newdomain.tld/${subdomain}.${olddomain}/g" /opt/verb/conf/webserver/sites-available/httpd/${subdomain}.${olddomain}.conf
+  /usr/bin/sed -i "s/newdomain.tld/${subdomain}.${olddomain}/g" /opt/verb/conf/webserver/sites-available/nginx/${subdomain}.${olddomain}.conf
   ## Server
   /opt/verb/serfs/ensiteapache -r ${subdomain}.${olddomain}
   /opt/verb/serfs/ensitenginx -r ${subdomain}.${olddomain}
@@ -98,13 +98,13 @@ wait
 
 # inkCert-LE
 ## This adds the declared domain to the end of the "domains =" line
-/bin/sed -i "s/, ${subdomain}.${olddomain}//g" /opt/verb/conf/inkcert/cli-ini/cli.${olddomain}.ini
-/bin/sed -i "/^domains =/ s/$/, ${subdomain}.${olddomain}/" /opt/verb/conf/inkcert/cli-ini/cli.${olddomain}.ini
+/usr/bin/sed -i "s/, ${subdomain}.${olddomain}//g" /opt/verb/conf/inkcert/cli-ini/cli.${olddomain}.ini
+/usr/bin/sed -i "/^domains =/ s/$/, ${subdomain}.${olddomain}/" /opt/verb/conf/inkcert/cli-ini/cli.${olddomain}.ini
 
 # inkCert status
 ## inkCert-CBSINGLE DONE for parent domain
-if /bin/grep -Fq "InkCerted=DONE_CBSINGLE" /opt/verb/conf/inkcert/cli-ini/siteinkcert.${olddomain}; then
-/bin/echo "FYI: inkCert has already been setup for this subdomain's parent domain with Certbot single-cert. But, that certificate cannot be used with this subdomain.
+if /usr/bin/grep -Fq "InkCerted=DONE_CBSINGLE" /opt/verb/conf/inkcert/cli-ini/siteinkcert.${olddomain}; then
+/usr/bin/echo "FYI: inkCert has already been setup for this subdomain's parent domain with Certbot single-cert. But, that certificate cannot be used with this subdomain.
 
 In summary: ${subdomain}.${olddomain} will not have SSL certs until you run:
   inkcertdocbsingle ${subdomain}.${olddomain}
diff --git a/serfs/installpostfixvmail b/serfs/installpostfixvmail
--- a/serfs/installpostfixvmail
+++ b/serfs/installpostfixvmail
@@ -24,7 +24,7 @@ voptflagpurpose=(  )
 dependencyinstall=(  )
 prerequesite=( "inkCert certs should be installled for at least the nameURI for this verber" )
 usedby=( installinkvmail )
-useserfs=( installspamassassin setinkcertmailcerts setinkcertmail inkvmailbaseaddrs inkdnsaddmail newinkdkim inkdnsaddinkdkim inkvmailsysmailbox )
+useserfs=( installspamassassin setinkcertmailcerts setinkcertmail inkvmailverbaddrs inkdnsaddmail newinkdkim inkdnsaddinkdkim inkvmailsysmailbox )
 useconfigs=( servernameip siteurilist servertype servermailpath )	# List config files of any kind used in this serf, please preserve order of appearance
 if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
 if [ -e "/opt/verb/mods/installpostfixvmail.replace" ]; then . /opt/verb/mods/installpostfixvmail.replace; return 0; fi # Replaces this script
@@ -38,19 +38,24 @@ if [ -e "/opt/verb/mods/installpostfixvmail.before" ]; then . /opt/verb/mods/ins
 . /opt/verb/conf/servermailpath
 
 # Check to see if already installed
-if [ "${ServerMailStatus}" = "VMAIL_SERVER" ]; then
+if [ "${ServerMailStatus}" = "MADDY_EMAIL_SERVER" ]; then
 /usr/bin/echo "
-Email server already installed.
+Maddy email server is already installed.
 "
 exit 0; fi
-if [ "${ServerMailStatus}" = "EMAIL_BACKUP_MX" ]; then
+if [ "${ServerMailStatus}" = "VMAIL_SERVER" ]; then
+/usr/bin/echo "
+Postfix vmail server already installed.
+"
+exit 0; fi
+if [[ "${ServerMailStatus}" =~ "_BACKUP_MX" ]]; then # Backup mail server could use Maddy or Postfix vmail or others, each needing its own, but must contain _BACKUP_MX in its setting
 /usr/bin/echo "
 Email server is already a backup server.
 "
 exit 0; fi
-if [ "${ServerMailStatus}" = "PMAIL_SERVER" ]; then
+if [ "${ServerMailStatus}" != "EMAIL_NOT_INSTALLED" ]; then
 /usr/bin/echo "
-Email server is already installed.
+Email server is already configured and cannot be installed.
 "
 exit 0; fi
 if ! /usr/bin/grep -Fq 'Email Control Records' /opt/verb/conf/inkdns/inkzones/db.${emailTLDURI}; then
@@ -70,8 +75,13 @@ exit 0; fi
 # Update Packages
 /usr/bin/pacman -Syyu --noconfirm --needed
 
+# Install Postfix server packages
+/usr/bin/pacman -S --noconfirm --needed postfix postfix-mysql postfix-lmdb dovecot pigeonhole mailutils cyrus-sasl opendkim msmtp
+e="$?"; [[ "$e" = "0" ]] || ( /usr/bin/echo 'Failed: !!' && exit "$e" )
+
 # Generate the mailpassword appendage
 mailpassgen="$(/usr/bin/pwgen -s -1 5)"
+
 ## Create the MySQL login .cnf
 /usr/bin/echo "[client]
 user = mail
@@ -81,8 +91,6 @@ host = localhost
 " > /opt/verb/conf/sql/mysqldb.vmail.cnf
 ## Set the config for backup
 /usr/bin/sed -i "s/ServerMailPassApg.*/ServerMailPassApg=\"${mailpassgen}\"/g" /opt/verb/conf/servermailpass
-
-# Packages already installed from make-verber-* postfix postfix-mysql dovecot php-imap spamassassin pigeonhole perl-cpanplus-dist-arch clamav razor cyrus-sasl opendkim
 
 # Utility directories
 /usr/bin/mkdir -p /srv/vip/vmail/customscripts /srv/vip/vmail/nativescripts /srv/vip/vmail/unsubscribe
@@ -262,7 +270,7 @@ if /usr/bin/grep -Fq "InkCerted=NO" /opt/verb/conf/inkcert/cli-ini/siteinkcert.$
 ## inkCert
 else
   /opt/verb/serfs/setinkcertmailcerts ${nameURI} inkvmail
-  /opt/verb/serfs/setinkcertmail ${nameURI} verber
+  /opt/verb/serfs/setinkcertmail ${nameURI} vmail
 fi
 
 # Create the mailbox table
@@ -521,9 +529,8 @@ fi
 # System domains & addresses
 ## Note: If the mail database needs to be reset, such as for a PostfixAdmin update, just run this after, then the results of this serf will be up to date
 ## Add base domains & addresses
-/opt/verb/serfs/inkvmailbaseaddrs
-## Setup PHP to send system mail
-#/opt/verb/serfs/inkvmailsysmailbox
+/opt/verb/serfs/inkvmailverbaddrs
+## Setup system mail
 /opt/verb/serfs/inkvmailsysmailboxmsmtp
 
 # Grand Restart
@@ -580,4 +587,4 @@ The email server is https://${emailTLDURI}
 
 
 
-if [ -e "/opt/verb/mods/installinkvmail.after" ]; then . /opt/verb/mods/installinkvmail.after; fi # Follows this script
+if [ -e "/opt/verb/mods/installpostfixvmail.after" ]; then . /opt/verb/mods/installpostfixvmail.after; fi # Follows this script
