inkCert checks cleanup

diff --git a/serfs/inkcertreqcb b/serfs/inkcertreqcb
--- a/serfs/inkcertreqcb
+++ b/serfs/inkcertreqcb
@@ -201,9 +201,16 @@ if [ ${ServerType} = "lemp" ] || [ ${ServerType} = "laemp" ]; then
       /usr/bin/systemctl start httpd
     fi
   fi
-  if [ "$(/usr/bin/systemctl is-active --quiet nginx)" != "0" ]; then
-    /usr/bin/echo "Nginx has a problem; can't get CB certs!"
-  fi
+  ### Make sure Nginx is running
+  count=0
+  while [ "$(/usr/bin/systemctl is-active --quiet nginx)" != "0" ]; do
+    if [ "${count}" -gt "40" ]; then
+      /usr/bin/echo "Nginx has a problem; can't get LE certs!"
+      exit 4
+    fi
+    /usr/bin/sleep 3
+    count=$((count + 1))
+  done
   
   /usr/bin/certbot --nginx certonly --preferred-challenges=dns --email ${InkCertEmail} --server https://acme-v02.api.letsencrypt.org/directory --agree-tos --no-eff-email --renew-by-default -d "${domain}" -d *.${domain}
 
diff --git a/serfs/inkcertreqle b/serfs/inkcertreqle
--- a/serfs/inkcertreqle
+++ b/serfs/inkcertreqle
@@ -188,13 +188,21 @@ if [ ${ServerType} = "lemp" ] || [ ${ServerType} = "laemp" ]; then
     fi
     /usr/bin/fuser -k 443/tcp # Thank you https://stackoverflow.com/a/49548253/10343144
     /usr/bin/systemctl start nginx
+
     if [ ${ServerType} = "laemp" ]; then
       /usr/bin/systemctl start httpd
     fi
   fi
-  if [ "$(/usr/bin/systemctl is-active --quiet nginx)" != "0" ]; then
-    /usr/bin/echo "Nginx has a problem; can't get LE certs!"
-  fi
+  ### Make sure Nginx is running
+  count=0
+  while [ "$(/usr/bin/systemctl is-active --quiet nginx)" != "0" ]; do
+    if [ "${count}" -gt "40" ]; then
+      /usr/bin/echo "Nginx has a problem; can't get LE certs!"
+      exit 4
+    fi
+    /usr/bin/sleep 3
+    count=$((count + 1))
+  done
   
   #yes n | /usr/bin/certbot --nginx certonly --expand --renew-by-default -c /opt/verb/conf/inkcert/cli-ini/cli.${domain}.ini
   /usr/bin/certbot --nginx certonly --expand --server https://acme-v02.api.letsencrypt.org/directory --agree-tos --no-eff-email --renew-by-default -c /opt/verb/conf/inkcert/cli-ini/cli.${domain}.ini
