inkCert checks cleanup

diff --git a/serfs/inkcertreqcb b/serfs/inkcertreqcb
--- a/serfs/inkcertreqcb
+++ b/serfs/inkcertreqcb
@@ -190,7 +190,8 @@ sleep 1
 # For wildcard certs, we need  acme.sh https://github.com/acmesh-official/acme.sh/blob/master/README.md#11-issue-wildcard-certificates
 if [ ${ServerType} = "lemp" ] || [ ${ServerType} = "laemp" ]; then
   #DEV avoid trouble with nginx: `[emerg] bind() to [::]:80 failed (98: Address already in use)` also: 0.0.0.0:80, 0.0.0.0:443, [::]:443
-  if [ "$(/usr/bin/systemctl is-active --quiet nginx)" != "0" ]; then
+  /usr/bin/systemctl is-active --quiet nginx
+  if [ "$?" != "0" ]; then
     /usr/bin/systemctl stop nginx
     if [ ${ServerType} = "laemp" ]; then
       /usr/bin/systemctl stop httpd
@@ -200,17 +201,17 @@ if [ ${ServerType} = "lemp" ] || [ ${ServerType} = "laemp" ]; then
     if [ ${ServerType} = "laemp" ]; then
       /usr/bin/systemctl start httpd
     fi
+    ### Make sure Nginx is running
+    count=0
+    while [ "$(/usr/bin/systemctl is-active --quiet nginx)" != "active" ]; do
+      if [ "${count}" -gt "40" ]; then
+        /usr/bin/echo "Nginx has a problem; can't get LE certs!"
+        exit 4
+      fi
+      /usr/bin/sleep 3
+      count=$((count + 1))
+    done
   fi
-  ### Make sure Nginx is running
-  count=0
-  while [ "$(/usr/bin/systemctl is-active --quiet nginx)" != "0" ]; do
-    if [ "${count}" -gt "40" ]; then
-      /usr/bin/echo "Nginx has a problem; can't get LE certs!"
-      exit 4
-    fi
-    /usr/bin/sleep 3
-    count=$((count + 1))
-  done
   
   /usr/bin/certbot --nginx certonly --preferred-challenges=dns --email ${InkCertEmail} --server https://acme-v02.api.letsencrypt.org/directory --agree-tos --no-eff-email --renew-by-default -d "${domain}" -d *.${domain}
 
diff --git a/serfs/inkcertreqcbsingle b/serfs/inkcertreqcbsingle
--- a/serfs/inkcertreqcbsingle
+++ b/serfs/inkcertreqcbsingle
@@ -189,7 +189,8 @@ sleep 1
 #DEV: The above shell command should work, once the non-server Named zones are synced with other nameservers, such as ns1.inkisaverb.com
 if [ ${ServerType} = "lemp" ] || [ ${ServerType} = "laemp" ]; then
   #DEV avoid trouble with nginx: `[emerg] bind() to [::]:80 failed (98: Address already in use)` also: 0.0.0.0:80, 0.0.0.0:443, [::]:443
-  if [ "$(/usr/bin/systemctl is-active --quiet nginx)" != "0" ]; then
+  /usr/bin/systemctl is-active --quiet nginx
+  if [ "$?" != "0" ]; then
     /usr/bin/systemctl stop nginx
     if [ ${ServerType} = "laemp" ]; then
       /usr/bin/systemctl stop httpd
@@ -199,17 +200,18 @@ if [ ${ServerType} = "lemp" ] || [ ${ServerType} = "laemp" ]; then
     if [ ${ServerType} = "laemp" ]; then
       /usr/bin/systemctl start httpd
     fi
+    ### Make sure Nginx is running
+    count=0
+    while [ "$(/usr/bin/systemctl is-active --quiet nginx)" != "active" ]; do
+      if [ "${count}" -gt "40" ]; then
+        /usr/bin/echo "Nginx has a problem; can't get LE certs!"
+        exit 4
+      fi
+      /usr/bin/sleep 3
+      count=$((count + 1))
+    done
   fi
-  ### Make sure Nginx is running
-  count=0
-  while [ "$(/usr/bin/systemctl is-active --quiet nginx)" != "0" ]; do
-    if [ "${count}" -gt "40" ]; then
-      /usr/bin/echo "Nginx has a problem; can't get LE certs!"
-      exit 4
-    fi
-    /usr/bin/sleep 3
-    count=$((count + 1))
-  done
+
   
   /usr/bin/certbot --nginx certonly --expand --server https://acme-v02.api.letsencrypt.org/directory --agree-tos --no-eff-email --renew-by-default -d "${domain}"
   #DEV Replaced by aboe line until dns keys can start working
diff --git a/serfs/inkcertreqle b/serfs/inkcertreqle
--- a/serfs/inkcertreqle
+++ b/serfs/inkcertreqle
@@ -181,7 +181,8 @@ sleep 1
 ## We may need `yes n |` as alternatives to --server https://acme-v02.api.letsencrypt.org/directory --agree-tos
 if [ ${ServerType} = "lemp" ] || [ ${ServerType} = "laemp" ]; then
   #DEV avoid trouble with nginx: `[emerg] bind() to [::]:80 failed (98: Address already in use)` also: 0.0.0.0:80, 0.0.0.0:443, [::]:443
-  if [ "$(/usr/bin/systemctl is-active --quiet nginx)" != "0" ]; then
+  /usr/bin/systemctl is-active --quiet nginx
+  if [ "$?" != "0" ]; then
     /usr/bin/systemctl stop nginx
     if [ ${ServerType} = "laemp" ]; then
       /usr/bin/systemctl stop httpd
@@ -192,17 +193,17 @@ if [ ${ServerType} = "lemp" ] || [ ${ServerType} = "laemp" ]; then
     if [ ${ServerType} = "laemp" ]; then
       /usr/bin/systemctl start httpd
     fi
+    ### Make sure Nginx is running
+    count=0
+    while [ "$(/usr/bin/systemctl is-active --quiet nginx)" != "active" ]; do
+      if [ "${count}" -gt "40" ]; then
+        /usr/bin/echo "Nginx has a problem; can't get LE certs!"
+        exit 4
+      fi
+      /usr/bin/sleep 3
+      count=$((count + 1))
+    done
   fi
-  ### Make sure Nginx is running
-  count=0
-  while [ "$(/usr/bin/systemctl is-active --quiet nginx)" != "0" ]; do
-    if [ "${count}" -gt "40" ]; then
-      /usr/bin/echo "Nginx has a problem; can't get LE certs!"
-      exit 4
-    fi
-    /usr/bin/sleep 3
-    count=$((count + 1))
-  done
   
   #yes n | /usr/bin/certbot --nginx certonly --expand --renew-by-default -c /opt/verb/conf/inkcert/cli-ini/cli.${domain}.ini
   /usr/bin/certbot --nginx certonly --expand --server https://acme-v02.api.letsencrypt.org/directory --agree-tos --no-eff-email --renew-by-default -c /opt/verb/conf/inkcert/cli-ini/cli.${domain}.ini
