Cleanup

diff --git a/serfs/inkdnsdig b/serfs/inkdnsdig
--- a/serfs/inkdnsdig
+++ b/serfs/inkdnsdig
@@ -49,6 +49,13 @@ if [ -z "$1" ]; then
   /bin/echo "Must specify a domain, I quit."; exit 5
 fi
 
+# Don't interrupt
+if [ -f "/opt/verb/dig/.digging" ]; then exit 0; fi
+
+# Prep
+/usr/bin/mkdir -p /opt/verb/dig
+/usr/bin/touch /opt/verb/dig/.digging
+
 # Domain
 domain="$1"
 output="/opt/verb/dig/digverbs-${domain}-$(date +'%Y-%m-%d_%H:%M:%S')"
@@ -56,26 +63,28 @@ outraw="${output}-raw"
 
 # Check mail?
 if [ -n "$2" ] && [ "$2" = "mail" ]; then
-  /usr/bin/dig @${ServerNS1DNS} ${domain} ns | tee -a ${outraw} | /usr/bin/grep "${ServerNS1DNS}" >> ${output} 2>&1 || ( /usr/bin/echo "No NS record for ${ServerNS1DNS}" && exit 4 ) >> ${output} 2>&1
-  /usr/bin/dig @${ServerNS1DNS} ${domain} ns | tee -a ${outraw} | /usr/bin/grep "${ServerNS2DNS}" >> ${output} 2>&1 || ( /usr/bin/echo "No NS record for ${ServerNS2DNS}" && exit 4 ) >> ${output} 2>&1
-  /usr/bin/dig @${ServerNS1DNS} ${domain} mx | tee -a ${outraw} | /usr/bin/grep MX | tee -a ${output} | /usr/bin/grep "mail.${domain}." >> ${output} 2>&1 || ( /usr/bin/echo "No MX record for ${domain}" && exit 4 ) >> ${output} 2>&1
-  /usr/bin/dig @${ServerNS1DNS} inkdkim._domainkey.${outraw} txt | tee -a ${output} | /usr/bin/grep TXT | tee -a ${output} | /usr/bin/grep "inkdkim" >> ${output} 2>&1 || ( /usr/bin/echo "No TXT record for DKIM" && exit 4 ) >> ${output} 2>&1
-  /usr/bin/dig @${ServerNS1DNS} ${domain} a | tee -a ${outraw} | /usr/bin/grep A | tee -a ${output} | /usr/bin/grep "${ServerIPv4}" >> ${output} 2>&1 || ( /usr/bin/echo "No A record for ${ServerIPv4}" && exit 4 ) >> ${output} 2>&1
-  /usr/bin/dig @${ServerNS1DNS} ${domain} aaaa | tee -a ${outraw} | /usr/bin/grep AAAA | tee -a ${output} | /usr/bin/grep "${ServerIPv6}" >> ${output} 2>&1 || ( /usr/bin/echo "No AAAA record for ${ServerIPv6}" && exit 4 ) >> ${output} 2>&1
-  /usr/bin/dig @${ServerNS1DNS} mail.${domain} a | tee -a ${outraw} | /usr/bin/grep A | tee -a ${output} | /usr/bin/grep "${ServerIPv4}" >> ${output} 2>&1 || ( /usr/bin/echo "No A mail record for ${ServerIPv4}" && exit 4 ) >> ${output} 2>&1
-  /usr/bin/dig @${ServerNS1DNS} mail.${domain} aaaa | tee -a ${outraw} | /usr/bin/grep AAAA | tee -a ${output} | /usr/bin/grep "${ServerIPv6}" >> ${output} 2>&1 || ( /usr/bin/echo "No AAAA mail record for ${ServerIPv6} " && exit 4 ) >> ${output} 2>&1
-  /usr/bin/dig @${ServerNS1DNS} smtp.${domain} a | tee -a ${outraw} | /usr/bin/grep A | tee -a ${output} | /usr/bin/grep "${ServerIPv4}" >> ${output} 2>&1 || ( /usr/bin/echo "No A smtp record for ${ServerIPv4}" && exit 4 ) >> ${output} 2>&1
-  /usr/bin/dig @${ServerNS1DNS} smtp.${domain} aaaa | tee -a ${outraw} | /usr/bin/grep AAAA | tee -a ${output} | /usr/bin/grep "${ServerIPv6}" >> ${output} 2>&1 || ( /usr/bin/echo "No AAAA smtp record for ${ServerIPv6} " && exit 4 ) >> ${output} 2>&1
-  /usr/bin/dig @${ServerNS1DNS} imap.${domain} a | tee -a ${outraw} | /usr/bin/grep A | tee -a ${output} | /usr/bin/grep "${ServerIPv4}" >> ${output} 2>&1 || ( /usr/bin/echo "No A imap record for ${ServerIPv4}" && exit 4 ) >> ${output} 2>&1
-  /usr/bin/dig @${ServerNS1DNS} imap.${domain} aaaa | tee -a ${outraw} | /usr/bin/grep AAAA | tee -a ${output} | /usr/bin/grep "${ServerIPv6}" >> ${output} 2>&1 || ( /usr/bin/echo "No AAAA imap record for ${ServerIPv6} " && exit 4 ) >> ${output} 2>&1
-  /usr/bin/dig @${ServerNS1DNS} pop3.${domain} a | tee -a ${outraw} | /usr/bin/grep A | tee -a ${output} | /usr/bin/grep "${ServerIPv4}" >> ${output} 2>&1 || ( /usr/bin/echo "No A pop3 record for ${ServerIPv4}" && exit 4 ) >> ${output} 2>&1
-  /usr/bin/dig @${ServerNS1DNS} pop3.${domain} aaaa | tee -a ${outraw} | /usr/bin/grep AAAA | tee -a ${output} | /usr/bin/grep "${ServerIPv6}" >> ${output} 2>&1 || ( /usr/bin/echo "No AAAA pop3 record for ${ServerIPv6}" && exit 4 ) >> ${output} 2>&1
+  /usr/bin/dig @${ServerNS1DNS} ${domain} ns | tee -a ${outraw} | /usr/bin/grep "${ServerNS1DNS}" >> ${output} 2>&1 || ( /usr/bin/echo "No NS record for ${ServerNS1DNS}" && /usr/bin/rm -f /opt/verb/dig/.digging && exit 4 ) >> ${output} 2>&1
+  /usr/bin/dig @${ServerNS1DNS} ${domain} ns | tee -a ${outraw} | /usr/bin/grep "${ServerNS2DNS}" >> ${output} 2>&1 || ( /usr/bin/echo "No NS record for ${ServerNS2DNS}" && /usr/bin/rm -f /opt/verb/dig/.digging && exit 4 ) >> ${output} 2>&1
+  /usr/bin/dig @${ServerNS1DNS} ${domain} mx | tee -a ${outraw} | /usr/bin/grep MX | tee -a ${output} | /usr/bin/grep "mail.${domain}." >> ${output} 2>&1 || ( /usr/bin/echo "No MX record for ${domain}" && /usr/bin/rm -f /opt/verb/dig/.digging && exit 4 ) >> ${output} 2>&1
+  /usr/bin/dig @${ServerNS1DNS} inkdkim._domainkey.${outraw} txt | tee -a ${output} | /usr/bin/grep TXT | tee -a ${output} | /usr/bin/grep "inkdkim" >> ${output} 2>&1 || ( /usr/bin/echo "No TXT record for DKIM" && /usr/bin/rm -f /opt/verb/dig/.digging && exit 4 ) >> ${output} 2>&1
+  /usr/bin/dig @${ServerNS1DNS} ${domain} a | tee -a ${outraw} | /usr/bin/grep A | tee -a ${output} | /usr/bin/grep "${ServerIPv4}" >> ${output} 2>&1 || ( /usr/bin/echo "No A record for ${ServerIPv4}" && /usr/bin/rm -f /opt/verb/dig/.digging && exit 4 ) >> ${output} 2>&1
+  /usr/bin/dig @${ServerNS1DNS} ${domain} aaaa | tee -a ${outraw} | /usr/bin/grep AAAA | tee -a ${output} | /usr/bin/grep "${ServerIPv6}" >> ${output} 2>&1 || ( /usr/bin/echo "No AAAA record for ${ServerIPv6}" && /usr/bin/rm -f /opt/verb/dig/.digging && exit 4 ) >> ${output} 2>&1
+  /usr/bin/dig @${ServerNS1DNS} mail.${domain} a | tee -a ${outraw} | /usr/bin/grep A | tee -a ${output} | /usr/bin/grep "${ServerIPv4}" >> ${output} 2>&1 || ( /usr/bin/echo "No A mail record for ${ServerIPv4}" && /usr/bin/rm -f /opt/verb/dig/.digging && exit 4 ) >> ${output} 2>&1
+  /usr/bin/dig @${ServerNS1DNS} mail.${domain} aaaa | tee -a ${outraw} | /usr/bin/grep AAAA | tee -a ${output} | /usr/bin/grep "${ServerIPv6}" >> ${output} 2>&1 || ( /usr/bin/echo "No AAAA mail record for ${ServerIPv6} " && /usr/bin/rm -f /opt/verb/dig/.digging && exit 4 ) >> ${output} 2>&1
+  /usr/bin/dig @${ServerNS1DNS} smtp.${domain} a | tee -a ${outraw} | /usr/bin/grep A | tee -a ${output} | /usr/bin/grep "${ServerIPv4}" >> ${output} 2>&1 || ( /usr/bin/echo "No A smtp record for ${ServerIPv4}" && /usr/bin/rm -f /opt/verb/dig/.digging && exit 4 ) >> ${output} 2>&1
+  /usr/bin/dig @${ServerNS1DNS} smtp.${domain} aaaa | tee -a ${outraw} | /usr/bin/grep AAAA | tee -a ${output} | /usr/bin/grep "${ServerIPv6}" >> ${output} 2>&1 || ( /usr/bin/echo "No AAAA smtp record for ${ServerIPv6} " && /usr/bin/rm -f /opt/verb/dig/.digging && exit 4 ) >> ${output} 2>&1
+  /usr/bin/dig @${ServerNS1DNS} imap.${domain} a | tee -a ${outraw} | /usr/bin/grep A | tee -a ${output} | /usr/bin/grep "${ServerIPv4}" >> ${output} 2>&1 || ( /usr/bin/echo "No A imap record for ${ServerIPv4}" && /usr/bin/rm -f /opt/verb/dig/.digging && exit 4 ) >> ${output} 2>&1
+  /usr/bin/dig @${ServerNS1DNS} imap.${domain} aaaa | tee -a ${outraw} | /usr/bin/grep AAAA | tee -a ${output} | /usr/bin/grep "${ServerIPv6}" >> ${output} 2>&1 || ( /usr/bin/echo "No AAAA imap record for ${ServerIPv6} " && /usr/bin/rm -f /opt/verb/dig/.digging && exit 4 ) >> ${output} 2>&1
+  /usr/bin/dig @${ServerNS1DNS} pop3.${domain} a | tee -a ${outraw} | /usr/bin/grep A | tee -a ${output} | /usr/bin/grep "${ServerIPv4}" >> ${output} 2>&1 || ( /usr/bin/echo "No A pop3 record for ${ServerIPv4}" && /usr/bin/rm -f /opt/verb/dig/.digging && exit 4 ) >> ${output} 2>&1
+  /usr/bin/dig @${ServerNS1DNS} pop3.${domain} aaaa | tee -a ${outraw} | /usr/bin/grep AAAA | tee -a ${output} | /usr/bin/grep "${ServerIPv6}" >> ${output} 2>&1 || ( /usr/bin/echo "No AAAA pop3 record for ${ServerIPv6}" && /usr/bin/rm -f /opt/verb/dig/.digging && exit 4 ) >> ${output} 2>&1
 else
-  /usr/bin/dig @${ServerNS1DNS} ${domain} ns | tee -a ${outraw} | /usr/bin/grep "${ServerNS1DNS}" >> ${output} 2>&1 || ( /usr/bin/echo "No NS record for ${ServerNS1DNS}" && exit 4 ) >> ${output} 2>&1
-  /usr/bin/dig @${ServerNS1DNS} ${domain} ns | tee -a ${outraw} | /usr/bin/grep "${ServerNS2DNS}" >> ${output} 2>&1 || ( /usr/bin/echo "No NS record for ${ServerNS2DNS}" && exit 4 ) >> ${output} 2>&1
-  /usr/bin/dig @${ServerNS1DNS} ${domain} a | tee -a ${outraw} | /usr/bin/grep A | tee -a ${output} | /usr/bin/grep "${ServerIPv4}" >> ${output} 2>&1 || ( /usr/bin/echo "No A record for ${ServerIPv4} " && exit 4 ) >> ${output} 2>&1
-  /usr/bin/dig @${ServerNS1DNS} ${domain} aaaa | tee -a ${outraw} | /usr/bin/grep AAAA | tee -a ${output} | /usr/bin/grep "${ServerIPv6}" >> ${output} 2>&1 || ( /usr/bin/echo "No AAAA record for ${ServerIPv6} " && exit 4 ) >> ${output} 2>&1
+  /usr/bin/dig @${ServerNS1DNS} ${domain} ns | tee -a ${outraw} | /usr/bin/grep "${ServerNS1DNS}" >> ${output} 2>&1 || ( /usr/bin/echo "No NS record for ${ServerNS1DNS}" && /usr/bin/rm -f /opt/verb/dig/.digging && exit 4 ) >> ${output} 2>&1
+  /usr/bin/dig @${ServerNS1DNS} ${domain} ns | tee -a ${outraw} | /usr/bin/grep "${ServerNS2DNS}" >> ${output} 2>&1 || ( /usr/bin/echo "No NS record for ${ServerNS2DNS}" && /usr/bin/rm -f /opt/verb/dig/.digging && exit 4 ) >> ${output} 2>&1
+  /usr/bin/dig @${ServerNS1DNS} ${domain} a | tee -a ${outraw} | /usr/bin/grep A | tee -a ${output} | /usr/bin/grep "${ServerIPv4}" >> ${output} 2>&1 || ( /usr/bin/echo "No A record for ${ServerIPv4} " && /usr/bin/rm -f /opt/verb/dig/.digging && exit 4 ) >> ${output} 2>&1
+  /usr/bin/dig @${ServerNS1DNS} ${domain} aaaa | tee -a ${outraw} | /usr/bin/grep AAAA | tee -a ${output} | /usr/bin/grep "${ServerIPv6}" >> ${output} 2>&1 || ( /usr/bin/echo "No AAAA record for ${ServerIPv6} " && /usr/bin/rm -f /opt/verb/dig/.digging && exit 4 ) >> ${output} 2>&1
 fi
 
+# Cleanup
+/usr/bin/rm -rf /opt/verb/dig
 
 if [ -e "/opt/verb/mods/inkdnsdig.after" ]; then . /opt/verb/mods/inkdnsdig.after; fi # Follows this script
