Pydio, SuiteCRM, OrangeHRM, Ampache, bugs

diff --git a/serfs/installampache b/serfs/installampache
--- a/serfs/installampache
+++ b/serfs/installampache
@@ -1,12 +1,36 @@
 #!/bin/bash
 #inkVerbSerf! verb.ink
 
-# This installs Ampache from inkisaverb.com/repo and links it to ampache....verb.kiwi
+# This installs Ampache from inkisaverb.com/repo and links it to sound....verb.kiwi
 
 # All options are optional, but must are sequential, omit last options first.
 
 # How to use:
-## ./installampache [dbase] [dbuser] [dbpassword]
+## ./installampache [ dbase - optional ] [ dbuser - optional ] [ dbpassword - optional ]
+
+# Eg:
+## ./installampache
+## ./installampache bestdbase bestdbuser besteverpass
+
+usagenotes="This installs Ampache from inkisaverb.com/repo and links it to sound....verb.kiwi"
+usageformat="installampache [ dbase - optional ] [ dbuser - optional ] [ dbpassword - optional ]"
+usageexample="installampache
+installampache bestdbase bestdbuser besteverpass"
+hierarchy=( primary )
+vsetnames=(  )
+vsettypes=(  )
+voptnames=( "Database" "Database user" "Database password" )
+vopttypes=( isSQLDatabasename isSQLDatabasename isSQLDatabasename )
+voptflags=(  )
+voptflagpurpose=(  )
+dependencyinstall=(  )
+prerequesite=(  )
+usedby=(  )
+useserfs=( inkget inkcert_ inkdriveapp )
+useconfigs=( servernameip siteurilist servertype )
+if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
+if [ -e "/opt/verb/mods/installampache.replace" ]; then . /opt/verb/mods/installampache.replace; return 0; fi # Replaces this script
+if [ -e "/opt/verb/mods/installampache.before" ]; then . /opt/verb/mods/installampache.before; fi # Precedes this script
 
 
 cVappName=ampache
@@ -14,10 +38,25 @@ cVappName=ampache
 # Include the configs
 . /opt/verb/conf/servernameip
 . /opt/verb/conf/siteurilist
+. /opt/verb/conf/servertype
 
 dBase=$1
 dBaseUser=$2
 dBPassword=$3
+
+# Check if already installed
+## Config
+if [ -f /opt/verb/conf/vapps/vapp.${cVappName} ]; then
+/usr/bin/echo "This is already installed."
+exit 0; fi
+## Directory
+if [ -d /srv/www/vapps/${cVappName} ]; then
+/usr/bin/echo "Ampache already exists in the system. If it isn't working, look deeper on the server. For now, doing nothing."
+exit 8; fi
+## Web server
+if [ ${ServerType} = "lamp" ]; then
+/usr/bin/echo "Only allowed with Nginx servers, LEMP or LAEMP; LAMP servers with Apache not allowed."
+exit 0; fi
 
 # Install
 cd /srv/www/vapps || exit 6
@@ -50,6 +89,53 @@ FLUSH PRIVILEGES;"
 #sed -i "s/database_password = password/database_password = ${dBPassword}/g" /srv/www/vapps/ampache/config/ampache.cfg.php
 ## Add the tables to the database
 #mysql --defaults-extra-file=/opt/verb/conf/sql/mysqlboss.cnf ${dBase} < /srv/www/vapps/ampache/sql/ampache.sql
+
+# Webserver setup
+if [ ${ServerType} = "laemp" ]; then
+  /usr/bin/mv /opt/verb/conf/webserver/sites-available/nginx/sound.${kiwiURI}.conf /opt/verb/conf/webserver/sites-available/nginx/sound.${kiwiURI}.conf.old
+  /usr/bin/mv /opt/verb/conf/webserver/sites-available/httpd/sound.${kiwiURI}.conf /opt/verb/conf/webserver/sites-available/httpd/sound.${kiwiURI}.conf.old
+  /usr/bin/cp /opt/verb/conf/site-files/conf/ampache.conf /opt/verb/conf/webserver/sites-available/nginx/sound.${kiwiURI}.conf
+  /usr/bin/rm -f /opt/verb/conf/webserver/sites-enabled/httpd/sound.${kiwiURI}.conf
+elif [ ${ServerType} = "lemp" ]; then
+  /usr/bin/mv /opt/verb/conf/webserver/sites-available/nginx/sound.${kiwiURI}.conf /opt/verb/conf/webserver/sites-available/nginx/sound.${kiwiURI}.conf.old
+  /usr/bin/cp /opt/verb/conf/site-files/conf/ampache.conf /opt/verb/conf/webserver/sites-available/nginx/sound.${kiwiURI}.conf
+fi
+
+# Setup for inkCert
+. /opt/verb/conf/inkcert/cli-ini/siteinkcert.${kiwiURI}
+case ${InkCerted} in
+  DONE_SC)
+  /opt/verb/serfs/inkcertaddsc sound.${kiwiURI} ${kiwiURI}
+  ;;
+  DONE_LE)
+  /opt/verb/serfs/inkcertaddle sound.${kiwiURI} ${kiwiURI}
+  ;;
+  DONE_CBSINGLE)
+  /opt/verb/serfs/inkcertaddcbsingle sound.${kiwiURI} ${kiwiURI}
+  ;;
+  DONE_CB)
+  /opt/verb/serfs/inkcertaddcb sound.${kiwiURI} ${kiwiURI}
+  ;;
+  NO|NOT_YET)
+    /usr/bin/echo "Nextcloud is currently using Snakeoil certs, ready for inkCert"
+  ;;
+  *)
+    if ! /usr/bin/grep -q "InkCerted=NO" /opt/verb/conf/inkcert/cli-ini/siteinkcert.${domain}; then
+      /usr/bin/echo "Something's wrong with the inkCert siteinkcert configs! Aborting"
+      exit 6
+    else
+      /usr/bin/echo "Nextcloud is currently using Snakeoil certs, ready for inkCert"
+    fi
+  ;;
+esac
+
+# Webserver restart
+if [ ${ServerType} = "laemp" ]; then
+  /usr/bin/systemctl restart nginx; wait
+  /usr/bin/systemctl restart httpd; wait
+elif [ ${ServerType} = "lemp" ]; then
+  /usr/bin/systemctl restart nginx; wait
+fi
 
 # Write the config for backup
 /bin/echo "#!/bin/bash
@@ -86,7 +172,7 @@ Next page: All info should be correct already
 
 *Make sure you look through Admin areas for some important options after you complete the installation and login.
 
-Go to http://ampache.${kiwiURI} to install.
+Go to https://sound.${kiwiURI} to install.
 "
 
 
diff --git a/serfs/installorangehrm b/serfs/installorangehrm
--- a/serfs/installorangehrm
+++ b/serfs/installorangehrm
@@ -1,12 +1,33 @@
 #!/bin/bash
 #inkVerbSerf! verb.ink
 
-# This downloads and installs OrangeHRM manually from inkisaverb.com/repo and linnks it to ....verb.blue
+# This downloads and installs OrangeHRM and links it to ....verb.red
 
 # All options are optional, but must are sequential, omit last options first.
 
 # How to use:
-## ./installorangehrm [dbase] [dbuser] [dbpassword]
+## ./installorangehrm [ dbase - optional ] [ dbuser - optional ] [ dbpassword - optional ]
+
+
+usagenotes="This downloads and installs OrangeHRM and links it to ....verb.red"
+usageformat="installorangehrm [ dbase - optional ] [ dbuser - optional ] [ dbpassword - optional ]"
+usageexample="installorangehrm
+installorangehrm bestdbase bestdbuser besteverpass"
+hierarchy=( primary )
+vsetnames=(  )
+vsettypes=(  )
+voptnames=( "Database" "Database user" "Database password" )
+vopttypes=( isSQLDatabasename isSQLDatabasename isSQLDatabasename )
+voptflags=(  )
+voptflagpurpose=(  )
+dependencyinstall=(  )
+prerequesite=(  )
+usedby=(  )
+useserfs=( inkget inkcert_ )
+useconfigs=( servernameip siteurilist servertype servermailpath )
+if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
+if [ -e "/opt/verb/mods/installorangehrm.replace" ]; then . /opt/verb/mods/installorangehrm.replace; return 0; fi # Replaces this script
+if [ -e "/opt/verb/mods/installorangehrm.before" ]; then . /opt/verb/mods/installorangehrm.before; fi # Precedes this script
 
 
 cVappName=orangehrm
@@ -14,6 +35,8 @@ cVappName=orangehrm
 # Include the configs
 . /opt/verb/conf/servernameip
 . /opt/verb/conf/siteurilist
+. /opt/verb/conf/servertype
+. /opt/verb/conf/servermailpath
 
 dBase=$1
 dBaseUser=$2
@@ -29,6 +52,10 @@ exit 0; fi
 if [ -d /srv/www/vapps/${cVappName} ]; then
 /bin/echo "OrangeHRM already exists in the system. If it isn't working, look deeper on the server. For now, doing nothing."
 exit 8; fi
+## Web server
+if [ ${ServerType} = "lamp" ]; then
+/usr/bin/echo "Only allowed with Nginx servers, LEMP or LAEMP; LAMP servers with Apache not allowed."
+exit 0; fi
 
 # Download and unpack the latest checked version from inkisaverb.com/repo
 cd /srv/www/vapps || exit 6
@@ -64,13 +91,75 @@ FLUSH PRIVILEGES;"
 #sed -i "s/dbpass   = 'orangehrm'/dbpass   = '${dBPassword}'/g" /srv/www/vapps/orangehrm/lib/confs/Conf.php
 
 # Firewall
-/usr/bin/ufw allow 3306
+#DEV No! because the SQL server is on localhost
+#/usr/bin/ufw allow 3306
 
 # Write the config for backup
 /bin/echo "#!/bin/bash
 appDBase=${dBase}
 appDDBUsr=${dBaseUser}
 appDDBPass=${dBPassword}" > /opt/verb/conf/vapps/vapp.${cVappName}
+
+# Webserver setup
+if [ ${ServerType} = "laemp" ]; then
+  /usr/bin/mv /opt/verb/conf/webserver/sites-available/nginx/hrm.${redURI286}.conf /opt/verb/conf/webserver/sites-available/nginx/hrm.${redURI286}.conf.old
+  /usr/bin/mv /opt/verb/conf/webserver/sites-available/httpd/hrm.${redURI286}.conf /opt/verb/conf/webserver/sites-available/httpd/hrm.${redURI286}.conf.old
+  /usr/bin/cp /opt/verb/conf/site-files/conf/orangehrm.conf /opt/verb/conf/webserver/sites-available/nginx/hrm.${redURI286}.conf
+  /usr/bin/rm -f /opt/verb/conf/webserver/sites-enabled/httpd/hrm.${redURI286}.conf
+elif [ ${ServerType} = "lemp" ]; then
+  /usr/bin/mv /opt/verb/conf/webserver/sites-available/nginx/hrm.${redURI286}.conf /opt/verb/conf/webserver/sites-available/nginx/hrm.${redURI286}.conf.old
+  /usr/bin/cp /opt/verb/conf/site-files/conf/orangehrm.conf /opt/verb/conf/webserver/sites-available/nginx/hrm.${redURI286}.conf
+fi
+
+# Setup for inkCert
+. /opt/verb/conf/inkcert/cli-ini/siteinkcert.${redURI286}
+case ${InkCerted} in
+  DONE_SC)
+  /opt/verb/serfs/inkcertaddsc hrm.${redURI286} ${redURI286}
+  ;;
+  DONE_LE)
+  /opt/verb/serfs/inkcertaddle hrm.${redURI286} ${redURI286}
+  ;;
+  DONE_CBSINGLE)
+  /opt/verb/serfs/inkcertaddcbsingle hrm.${redURI286} ${redURI286}
+  ;;
+  DONE_CB)
+  /opt/verb/serfs/inkcertaddcb hrm.${redURI286} ${redURI286}
+  ;;
+  NO|NOT_YET)
+    /usr/bin/echo "OrangeHRM is currently using Snakeoil certs, ready for inkCert"
+  ;;
+  *)
+    if ! /usr/bin/grep -q "InkCerted=NO" /opt/verb/conf/inkcert/cli-ini/siteinkcert.${domain}; then
+      /usr/bin/echo "Something's wrong with the inkCert siteinkcert configs! Aborting"
+      exit 6
+    else
+      /usr/bin/echo "OrangeHRM is currently using Snakeoil certs, ready for inkCert"
+    fi
+  ;;
+esac
+
+# Webserver restart
+if [ ${ServerType} = "laemp" ]; then
+  /usr/bin/systemctl restart nginx; wait
+  /usr/bin/systemctl restart httpd; wait
+elif [ ${ServerType} = "lemp" ]; then
+  /usr/bin/systemctl restart nginx; wait
+fi
+
+# Use msmtp for a real SMTP address
+## Postfix vmail?
+if [ "${ServerMailStatus}" = "VMAIL_SERVER" ]; then
+  /opt/verb/serfs/inkvmailsysorangehrm
+
+## Maddy email?
+  elif [ "${ServerMailStatus}" = "MADDY_EMAIL_SERVER" ]; then
+  /opt/verb/serfs/inkemailsysorangehrm
+
+## Neither
+else
+  /usr/bin/echo "No email server detected, so not configuring email settings."
+fi
 
 /bin/echo "These are setup:
 
@@ -82,7 +171,7 @@ Database user password: ${dBPassword}
 *Select \"Existing database\" in setup to make life easier, if you want.
 *Enable Data Encryption? - Probably NOT!
 
-Go to http://hrm.${redURI} to install.
+Go to https://hrm.${redURI} to install.
 "
 
 
diff --git a/serfs/installsuitecrm b/serfs/installsuitecrm
--- a/serfs/installsuitecrm
+++ b/serfs/installsuitecrm
@@ -1,18 +1,45 @@
 #!/bin/bash
 #inkVerbSerf! verb.ink
 
-# This downloads and installs the current verified version of suiteCRM from inkisaverb.com/repo to crm.your-name.verb.red
+# This downloads and installs SuiteCRM and links it to ....verb.red
 
 # All options are optional, but must are sequential, omit last options first.
 
 # How to use:
-## ./installsuitecrm [dbase] [dbuser] [dbpassword]
+## ./installsuitecrm [ dbase - optional ] [ dbuser - optional ] [ dbpassword - optional ]
+
+# Eg:
+## ./installsuitecrm
+## ./installsuitecrm bestdbase bestdbuser besteverpass
+
+usagenotes="This downloads and installs SuiteCRM and links it to ....verb.red"
+usageformat="installsuitecrm [ dbase - optional ] [ dbuser - optional ] [ dbpassword - optional ]"
+usageexample="installsuitecrm
+installsuitecrm bestdbase bestdbuser besteverpass"
+hierarchy=( primary )
+vsetnames=(  )
+vsettypes=(  )
+voptnames=( "Database" "Database user" "Database password" )
+vopttypes=( isSQLDatabasename isSQLDatabasename isSQLDatabasename )
+voptflags=(  )
+voptflagpurpose=(  )
+dependencyinstall=(  )
+prerequesite=(  )
+usedby=(  )
+useserfs=( inkget inkcert_ )
+useconfigs=( servernameip siteurilist servertype servermailpath )
+if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
+if [ -e "/opt/verb/mods/installsuitecrm.replace" ]; then . /opt/verb/mods/installsuitecrm.replace; return 0; fi # Replaces this script
+if [ -e "/opt/verb/mods/installsuitecrm.before" ]; then . /opt/verb/mods/installsuitecrm.before; fi # Precedes this script
 
 
 cVappName=suitecrm
 
-# Include the config
+# Include the configs
+. /opt/verb/conf/servernameip
 . /opt/verb/conf/siteurilist
+. /opt/verb/conf/servertype
+. /opt/verb/conf/servermailpath
 
 dBase=$1
 dBaseUser=$2
@@ -28,9 +55,10 @@ exit 0; fi
 if [ -d /srv/www/vapps/${cVappName} ]; then
 /bin/echo "SuiteCRM already exists in the system. If it isn't working, look deeper on the server. For now, doing nothing."
 exit 8; fi
-
-# Include the config file
-. /opt/verb/conf/servernameip
+## Web server
+if [ ${ServerType} = "lamp" ]; then
+/usr/bin/echo "Only allowed with Nginx servers, LEMP or LAEMP; LAMP servers with Apache not allowed."
+exit 0; fi
 
 # This does not create a database, only an administrator since suiteCRM will create that automatically
 
@@ -64,6 +92,68 @@ appDBase=${dBase}
 appDDBUsr=${dBaseUser}
 appDDBPass=${dBPassword}" > /opt/verb/conf/vapps/vapp.${cVappName}
 
+# Webserver setup
+if [ ${ServerType} = "laemp" ]; then
+  /usr/bin/mv /opt/verb/conf/webserver/sites-available/nginx/crm.${redURI286}.conf /opt/verb/conf/webserver/sites-available/nginx/crm.${redURI286}.conf.old
+  /usr/bin/mv /opt/verb/conf/webserver/sites-available/httpd/crm.${redURI286}.conf /opt/verb/conf/webserver/sites-available/httpd/crm.${redURI286}.conf.old
+  /usr/bin/cp /opt/verb/conf/site-files/conf/suitcrm.conf /opt/verb/conf/webserver/sites-available/nginx/crm.${redURI286}.conf
+  /usr/bin/rm -f /opt/verb/conf/webserver/sites-enabled/httpd/crm.${redURI286}.conf
+elif [ ${ServerType} = "lemp" ]; then
+  /usr/bin/mv /opt/verb/conf/webserver/sites-available/nginx/crm.${redURI286}.conf /opt/verb/conf/webserver/sites-available/nginx/crm.${redURI286}.conf.old
+  /usr/bin/cp /opt/verb/conf/site-files/conf/suitcrm.conf /opt/verb/conf/webserver/sites-available/nginx/crm.${redURI286}.conf
+fi
+
+# Setup for inkCert
+. /opt/verb/conf/inkcert/cli-ini/siteinkcert.${redURI286}
+case ${InkCerted} in
+  DONE_SC)
+  /opt/verb/serfs/inkcertaddsc crm.${redURI286} ${redURI286}
+  ;;
+  DONE_LE)
+  /opt/verb/serfs/inkcertaddle crm.${redURI286} ${redURI286}
+  ;;
+  DONE_CBSINGLE)
+  /opt/verb/serfs/inkcertaddcbsingle crm.${redURI286} ${redURI286}
+  ;;
+  DONE_CB)
+  /opt/verb/serfs/inkcertaddcb crm.${redURI286} ${redURI286}
+  ;;
+  NO|NOT_YET)
+    /usr/bin/echo "SuireCRM is currently using Snakeoil certs, ready for inkCert"
+  ;;
+  *)
+    if ! /usr/bin/grep -q "InkCerted=NO" /opt/verb/conf/inkcert/cli-ini/siteinkcert.${domain}; then
+      /usr/bin/echo "Something's wrong with the inkCert siteinkcert configs! Aborting"
+      exit 6
+    else
+      /usr/bin/echo "SuireCRM is currently using Snakeoil certs, ready for inkCert"
+    fi
+  ;;
+esac
+
+# Webserver restart
+if [ ${ServerType} = "laemp" ]; then
+  /usr/bin/systemctl restart nginx; wait
+  /usr/bin/systemctl restart httpd; wait
+elif [ ${ServerType} = "lemp" ]; then
+  /usr/bin/systemctl restart nginx; wait
+fi
+
+# Use msmtp for a real SMTP address
+## Postfix vmail?
+if [ "${ServerMailStatus}" = "VMAIL_SERVER" ]; then
+  /opt/verb/serfs/inkvmailsyssuitecrm
+
+## Maddy email?
+  elif [ "${ServerMailStatus}" = "MADDY_EMAIL_SERVER" ]; then
+  /opt/verb/serfs/inkemailsyssuitecrm
+
+## Neither
+else
+  /usr/bin/echo "No email server detected, so not configuring email settings."
+fi
+
+
 /bin/echo "These are setup:
 
 Database: ${dBase}
@@ -75,7 +165,7 @@ Database password: ${dBPassword}
 
 *Choose \"Provide Existing User\" BEFORE entering above information.
 
-Go to the http://crm.${redURI} site to install.
+Go to the https://crm.${redURI} site to install.
 "
 
 
