Better ink help

diff --git a/serfs/installnextcloud b/serfs/installnextcloud
--- a/serfs/installnextcloud
+++ b/serfs/installnextcloud
@@ -244,15 +244,15 @@ After, you may want to run setnextcloudbfdoff to disable brute force detection i
 # inkDrive? (last so above message shows, even if we need to exit non-zero next)
 if [ -f "/opt/verb/conf/inkdrive/inkdriveinfo" ]; then
   . /opt/verb/conf/inkdrive/inkdriveinfo
-fi
-if [ "${InkDriveNC}" != "off" ]; then
-  /usr/bin/echo "Mounting 'data' to a drive..."
-  /opt/verb/serfs/inkdriveapp "${cVappName}" "${InkDriveNC}"
-  if [ "$?" = 0 ]; then
-    /usr/bin/echo "InkDrive=\"${InkDriveNC}\"" >> /opt/verb/conf/vapps/vapp.${cVappName}
-  else
-    /usr/bin/echo "inkDrive hosting is expected, but unable to host Nextcloud on the drive. Something is very wrong!"
-    exit 6
+  if [ "${InkDriveNC}" != "off" ]; then
+    /usr/bin/echo "Mounting 'data' to a drive..."
+    /opt/verb/serfs/inkdriveapp "${cVappName}" "${InkDriveNC}"
+    if [ "$?" = 0 ]; then
+      /usr/bin/echo "InkDrive=\"${InkDriveNC}\"" >> /opt/verb/conf/vapps/vapp.${cVappName}
+    else
+      /usr/bin/echo "inkDrive hosting is expected, but unable to host Nextcloud on the drive. Something is very wrong!"
+      exit 6
+    fi
   fi
 fi
 
diff --git a/serfs/installwp b/serfs/installwp
--- a/serfs/installwp
+++ b/serfs/installwp
@@ -145,15 +145,15 @@ Go to https://${domain}/wp-admin/index.php to install.
 # inkDrive? (last so above message shows, even if we need to exit non-zero next)
 if [ -f "/opt/verb/conf/inkdrive/inkdriveinfo" ]; then
   . /opt/verb/conf/inkdrive/inkdriveinfo
-fi
-if [ "${InkDriveWP}" != "off" ]; then
-  /usr/bin/echo "Mounting 'wp-content' to a drive..."
-  /opt/verb/serfs/inkdriveapp "${cVappName}.${domain}" "${InkDriveWP}"
-  if [ "$?" = 0 ]; then
-    /usr/bin/echo "InkDrive=\"${InkDriveWP}\"" >> /opt/verb/conf/vapps/vapp.${cVappName}.${domain}
-  else
-    /usr/bin/echo "inkDrive hosting is expected, but unable to host WP on the drive. Something is very wrong!"
-    exit 6
+  if [ "${InkDriveWP}" != "off" ]; then
+    /usr/bin/echo "Mounting 'wp-content' to a drive..."
+    /opt/verb/serfs/inkdriveapp "${cVappName}.${domain}" "${InkDriveWP}"
+    if [ "$?" = 0 ]; then
+      /usr/bin/echo "InkDrive=\"${InkDriveWP}\"" >> /opt/verb/conf/vapps/vapp.${cVappName}.${domain}
+    else
+      /usr/bin/echo "inkDrive hosting is expected, but unable to host WP on the drive. Something is very wrong!"
+      exit 6
+    fi
   fi
 fi
 
