Serving parked domains - better exit workflow

diff --git a/serfs/rinkadddomain b/serfs/rinkadddomain
--- a/serfs/rinkadddomain
+++ b/serfs/rinkadddomain
@@ -38,7 +38,7 @@ if [ "$RinkConfigured" = "rink" ] && [ -f "/opt/rink/run/addmasterdomain" ]; the
 	exit 0
 elif [ "$RinkConfigured" != "true" ]; then
 	echo "Rink NS nameserver keys not configured, DNS nameserver zone files must be updated manually"
-	exit 0
+	exit 5
 fi
 
 # Add the configs to the domains/ folder on the NS nameservers
@@ -52,6 +52,7 @@ sdnsIPv6Cmp="${ServerIPv6}"
 sdnsIPv6ARPA="${ServerARPAIPv6}"
 EOF
 EOS
+e="$?"; [[ "$e" = "0" ]] || /usr/bin/echo "rinkadddomain failed to add ${slavedomain} to NS1"; exit "$e"
 /usr/bin/ssh -T ns2 <<EOS
 /usr/bin/cat <<EOF > /srv/sns/${ServerName}-${ServerTLD}/domains/${slavedomain}
 sdnsDomain="${slavedomain}"
@@ -62,5 +63,6 @@ sdnsIPv6Cmp="${ServerIPv6}"
 sdnsIPv6ARPA="${ServerARPAIPv6}"
 EOF
 EOS
+e="$?"; [[ "$e" = "0" ]] || /usr/bin/echo "rinkadddomain failed to add ${slavedomain} to NS2"; exit "$e"
 
 if [ -e "/opt/verb/mods/rinkadddomain.after" ]; then . /opt/verb/mods/rinkadddomain.after; fi # Follows this script
