UUID for mounting

diff --git a/serfs/webcgi b/serfs/webcgi
--- a/serfs/webcgi
+++ b/serfs/webcgi
@@ -12,8 +12,17 @@ domain=$2
 
 . /opt/verb/conf/servertype
 
+# Check if it exists
+if [ ${ServerType} = "lamp" ] || [ ${ServerType} = "laemp" ]; then
+	if [ ! -e "/opt/verb/conf/webserver/sites-available/httpd/${domain}.conf" ]; then
+		/usr/bin/echo "${domain} not found."
+		exit 8
+	fi
+fi
+
 if [ ${ServerType} = "lemp" ]; then
 	/bin/echo "CGI not allowed on LEMP servers."
+	exit 9
 
 elif [ ${ServerType} = "lamp" ] || [ ${ServerType} = "laemp" ]; then
 
diff --git a/serfs/webhttps b/serfs/webhttps
--- a/serfs/webhttps
+++ b/serfs/webhttps
@@ -13,10 +13,24 @@ domain=$2
 
 . /opt/verb/conf/servertype
 
-if [ "$1" = "on" ]; then
+# Check if it exists
+## Nginx
+if [ ${ServerType} = "lemp" ] || [ ${ServerType} = "laemp" ]; then
+	if [ ! -e "/opt/verb/conf/webserver/sites-available/nginx/${domain}.conf" ]; then
+		/usr/bin/echo "${domain} not found."
+		exit 8
+	fi
+## Apache
+elif [ ${ServerType} = "lamp" ]; then
+	if [ ! -e "/opt/verb/conf/webserver/sites-available/httpd/${domain}.conf" ]; then
+		/usr/bin/echo "${domain} not found."
+		exit 8
+	fi
+fi
 
+if [ "$1" = "on" ]; then
+	# Nginx
 	if [ ${ServerType} = "lemp" ] || [ ${ServerType} = "laemp" ]; then
-		# Nginx
 		## Check to see if "fixhttps" has already been added
 		if /bin/grep -q "##INKHTTPSFIX=fixed" /opt/verb/conf/webserver/sites-available/nginx/${domain}.conf; then
 			/bin/systemctl restart nginx; wait
@@ -48,8 +62,9 @@ if [ "$1" = "on" ]; then
 
 			/bin/echo "${domain} now redirects all http traffic to SSL-secure https."
 		fi
-
+	# Apache
 	elif [ ${ServerType} = "lamp" ]; then
+
 		# Check to see if "fixhttps" has already been added
 		if /bin/grep -q "##INKHTTPSFIX=fixed" /opt/verb/conf/webserver/sites-available/httpd/${domain}.conf; then
 			/usr/bin/systemctl restart httpd
@@ -92,10 +107,9 @@ if [ "$1" = "on" ]; then
 	fi
 
 elif [ "$1" = "off" ]; then
-
+	# Nginx
 	if [ ${ServerType} = "lemp" ] || [ ${ServerType} = "laemp" ]; then
-	  # Nginx
-		## Verify that it has been fixed
+	  ## Verify that it has been fixed
 	  if /bin/grep -q "##INKHTTPSFIX=fixed" /opt/verb/conf/webserver/sites-available/nginx/${domain}.conf; then
 
 	    # Replace it with the original file
@@ -117,7 +131,7 @@ elif [ "$1" = "off" ]; then
 	    /bin/echo "${domain} doesn't have the https fix. Doing nothing."
 	    exit 0
 	  fi
-
+	# Apache
 	elif [ ${ServerType} = "lamp" ]; then
 	  # Verify that it has been fixed
 	  if /bin/grep -q "##INKHTTPSFIX=fixed" /opt/verb/conf/webserver/sites-available/httpd/${domain}.conf; then
diff --git a/serfs/webvipcgi b/serfs/webvipcgi
--- a/serfs/webvipcgi
+++ b/serfs/webvipcgi
@@ -13,6 +13,14 @@
 . /opt/verb/conf/siteurilist
 . /opt/verb/conf/servertype
 
+# Check if it exists
+if [ ${ServerType} = "lamp" ] || [ ${ServerType} = "laemp" ]; then
+	if [ ! -e "/srv/www/verb/vip.v" ]; then
+		/usr/bin/echo "vip not found. Something is very wrong."
+		exit 6
+	fi
+fi
+
 if [ ${ServerType} = "lemp" ]; then
   /bin/echo "CGI not allowed on LEMP servers anyway. Nothing to do."
 
diff --git a/serfs/webwild b/serfs/webwild
--- a/serfs/webwild
+++ b/serfs/webwild
@@ -12,6 +12,21 @@ domain=$2
 
 . /opt/verb/conf/servertype
 
+# Check if it exists
+## Nginx
+if [ ${ServerType} = "lemp" ]; then
+	if [ ! -e "/opt/verb/conf/webserver/sites-available/nginx/${domain}.conf" ]; then
+		/usr/bin/echo "${domain} not found."
+		exit 8
+	fi
+## Apache
+elif [ ${ServerType} = "lamp" ] || [ ${ServerType} = "laemp" ]; then
+	if [ ! -e "/opt/verb/conf/webserver/sites-available/httpd/${domain}.conf" ]; then
+		/usr/bin/echo "${domain} not found."
+		exit 8
+	fi
+fi
+
 if [ "$1" = "on" ]; then
 
 	if [ ${ServerType} = "lemp" ]; then
