VOLEP

diff --git a/inst/make-preverber b/inst/make-preverber
--- a/inst/make-preverber
+++ b/inst/make-preverber
@@ -33,7 +33,7 @@ exit 8; fi
 
 # Install tools (tmux for unstable ssh connections, reconnect with tmux attach)
 /usr/bin/pacman -S --noconfirm --needed tmux ntp pwgen zip unzip htop which vim curl wget make cronie gcc autoconf imagemagick git parted perl net-tools inetutils man sudo
-if [ "$?" != "0" ]; then e="$?"; /usr/bin/echo 'Failed: !!'; exit "$e"; fi
+e="$?"; [[ "$e" = "0" ]] || /usr/bin/echo 'Failed: !!'; exit "$e"
 
 # Enable NTP for accurate time (the standard service is commented below)
 #/usr/bin/systemctl enable --now systemd-timesyncd
@@ -92,7 +92,7 @@ sed -i "s/#PermitRootLogin.*/PermitRootLogin prohibit-password/" /etc/ssh/sshd_c
 
 # AUR package manager
 /usr/bin/pacman -S --noconfirm --needed base-devel # Dependencies
-if [ "$?" != "0" ]; then e="$?"; /usr/bin/echo 'Failed: !!'; exit "$e"; fi
+e="$?"; [[ "$e" = "0" ]] || /usr/bin/echo 'Failed: !!'; exit "$e"
 cd /opt/verb/worker || exit 6
 /usr/bin/su worker -c '/usr/bin/git clone https://aur.archlinux.org/yay-bin.git'
 cd yay-bin || exit 6
diff --git a/inst/make-verber-lamp b/inst/make-verber-lamp
--- a/inst/make-verber-lamp
+++ b/inst/make-verber-lamp
@@ -112,7 +112,7 @@ cd $OLDPWD || exit 6
 
 # Apache
 /usr/bin/pacman -S --noconfirm --needed apache
-if [ "$?" != "0" ]; then e="$?"; /usr/bin/echo 'Failed: !!'; exit "$e"; fi
+e="$?"; [[ "$e" = "0" ]] || /usr/bin/echo 'Failed: !!'; exit "$e"
 if [ ! -d "/etc/httpd" ]; then echo "Apache installed, but /etc/httpd does not exist!"; exit 6; fi
 
 ## Apache Settings
@@ -135,7 +135,7 @@ EOF
 
 ## PHP
 /usr/bin/pacman -S --noconfirm --needed php php-fpm
-if [ "$?" != "0" ]; then e="$?"; /usr/bin/echo 'Failed: !!'; exit "$e"; fi
+e="$?"; [[ "$e" = "0" ]] || /usr/bin/echo 'Failed: !!'; exit "$e"
 
 ## PHP-FPM
 /usr/bin/cat <<'EOF' > /etc/httpd/conf/extra/php-fpm.conf
@@ -165,7 +165,7 @@ echo 'security.limit_extensions = .php .html .htm .shtml' >> /etc/php/php-fpm.d/
 
 ## PHP extras
 /usr/bin/pacman -S --noconfirm --needed pkg-config php-gd php-apcu nginx-mod-headers-more fcgiwrap php-imagick php-intl php-pspell
-if [ "$?" != "0" ]; then e="$?"; /usr/bin/echo 'Failed: !!'; exit "$e"; fi
+e="$?"; [[ "$e" = "0" ]] || /usr/bin/echo 'Failed: !!'; exit "$e"
 
 ## Services
 /usr/bin/systemctl enable php-fpm; wait
@@ -177,7 +177,7 @@ if [ "$?" != "0" ]; then e="$?"; /usr/bin/echo 'Failed: !!'; exit "$e"; fi
 
 # MySQL (viz MariaDB)
 /usr/bin/pacman -S --noconfirm --needed mariadb
-if [ "$?" != "0" ]; then e="$?"; /usr/bin/echo 'Failed: !!'; exit "$e"; fi
+e="$?"; [[ "$e" = "0" ]] || /usr/bin/echo 'Failed: !!'; exit "$e"
 /usr/bin/mariadb-install-db --user=mysql --basedir=/usr --datadir=/var/lib/mysql
 /usr/bin/pacman -S --noconfirm --needed perl-dbd-mysql # For Spamassassin's database
 ## Start it now so it works when we run the secure installation
@@ -218,7 +218,7 @@ LimitMEMLOCK=infinity" >> /etc/systemd/system/mariadb.service
 
 # Firewall
 /usr/bin/pacman -S --noconfirm --needed ufw
-if [ "$?" != "0" ]; then e="$?"; /usr/bin/echo 'Failed: !!'; exit "$e"; fi
+e="$?"; [[ "$e" = "0" ]] || /usr/bin/echo 'Failed: !!'; exit "$e"
 /usr/bin/systemctl enable ufw; wait
 /usr/bin/systemctl start ufw; wait
 /usr/bin/ufw allow 80/tcp
@@ -273,7 +273,7 @@ if [ "$?" != "0" ]; then e="$?"; /usr/bin/echo 'Failed: !!'; exit "$e"; fi
 
 # Monit
 /usr/bin/pacman -S --noconfirm --needed monit
-if [ "$?" != "0" ]; then e="$?"; /usr/bin/echo 'Failed: !!'; exit "$e"; fi
+e="$?"; [[ "$e" = "0" ]] || /usr/bin/echo 'Failed: !!'; exit "$e"
 ## Copy configs (These seem to have precedence, files in /etc/monit seem to conflict with them but may be u/usr/bin/sed instead
 /usr/bin/mkdir -p /etc/monit/monitrc.d
 #/usr/bin/sed -i "s?#  include /etc/monit.d?  include /etc/monit/monit.d?" /etc/monitrc
@@ -291,23 +291,23 @@ if [ "$?" != "0" ]; then e="$?"; /usr/bin/echo 'Failed: !!'; exit "$e"; fi
 
 # Pre-install Go (may be redundand as Go is a dependency in make-preverber)
 /usr/bin/pacman -S --noconfirm --needed go
-if [ "$?" != "0" ]; then e="$?"; /usr/bin/echo 'Failed: !!'; exit "$e"; fi
+e="$?"; [[ "$e" = "0" ]] || /usr/bin/echo 'Failed: !!'; exit "$e"
 
 # Pre-install Postfix server packages
 /usr/bin/pacman -S --noconfirm --needed postfix postfix-mysql dovecot pigeonhole mailutils cyrus-sasl opendkim msmtp
-if [ "$?" != "0" ]; then e="$?"; /usr/bin/echo 'Failed: !!'; exit "$e"; fi
+e="$?"; [[ "$e" = "0" ]] || /usr/bin/echo 'Failed: !!'; exit "$e"
 
 # Pre-install inkCert-LE
 /usr/bin/pacman -S --noconfirm --needed certbot certbot-apache
-if [ "$?" != "0" ]; then e="$?"; /usr/bin/echo 'Failed: !!'; exit "$e"; fi
+e="$?"; [[ "$e" = "0" ]] || /usr/bin/echo 'Failed: !!'; exit "$e"
 
 # Pre-install inkDNS
 /usr/bin/pacman -S --noconfirm --needed bind dnsutils certbot-dns-rfc2136
-if [ "$?" != "0" ]; then e="$?"; /usr/bin/echo 'Failed: !!'; exit "$e"; fi
+e="$?"; [[ "$e" = "0" ]] || /usr/bin/echo 'Failed: !!'; exit "$e"
 
 # Pre-install vsftpd
 /usr/bin/pacman -S --noconfirm --needed vsftpd
-if [ "$?" != "0" ]; then e="$?"; /usr/bin/echo 'Failed: !!'; exit "$e"; fi
+e="$?"; [[ "$e" = "0" ]] || /usr/bin/echo 'Failed: !!'; exit "$e"
 
 # Remove unneeded packages
 /usr/bin/pacman -Qdt --noconfirm
