Production ready

diff --git a/inst/make-preverber b/inst/make-preverber
--- a/inst/make-preverber
+++ b/inst/make-preverber
@@ -33,7 +33,7 @@ exit 8; fi
 
 # Install tools
 /usr/bin/pacman -S --noconfirm --needed ntp pwgen zip unzip htop which vim curl wget make cronie gcc autoconf imagemagick git parted net-tools inetutils man sudo
-if [ "$?" != "0" ]; then /usr/bin/echo 'Failed: !!'; exit 4; fi
+e="$?"; [[ "$e" = "0" ]] || /usr/bin/echo 'Failed: !!' && exit "$e"
 
 # Enable NTP for accurate time (the standard service is commented below)
 #/usr/bin/systemctl enable --now systemd-timesyncd
@@ -95,7 +95,7 @@ sed -i "s/#PermitRootLogin.*/PermitRootLogin prohibit-password/" /etc/ssh/sshd_c
 
 # AUR package manager
 /usr/bin/pacman -S --noconfirm --needed base-devel # Dependencies
-if [ "$?" != "0" ]; then /usr/bin/echo 'Failed: !!'; exit 4; fi
+e="$?"; [[ "$e" = "0" ]] || /usr/bin/echo 'Failed: !!' && exit "$e"
 cd /opt/verb/worker || exit 0
 /usr/bin/su worker -c '/usr/bin/git clone https://aur.archlinux.org/yay.git'
 cd yay || exit 0
diff --git a/inst/make-verber-lemp b/inst/make-verber-lemp
--- a/inst/make-verber-lemp
+++ b/inst/make-verber-lemp
@@ -108,7 +108,7 @@ cd $OLDPWD || exit 0
 
 ## Nginx
 /usr/bin/pacman -S --noconfirm --needed nginx
-if [ "$?" != "0" ]; then /usr/bin/echo 'Failed: !!'; exit 4; fi
+e="$?"; [[ "$e" = "0" ]] || /usr/bin/echo 'Failed: !!' && exit "$e"
 /usr/bin/mkdir -p /opt/verb/conf/webserver/nginx/sites-available /opt/verb/conf/webserver/nginx/sites-enabled /etc/nginx
 /usr/bin/cp /opt/verb/inst/webserver/lemp-sites-available/*.conf /opt/verb/conf/webserver/nginx/sites-available/
 
@@ -195,7 +195,7 @@ fi
 
 ## PHP
 /usr/bin/pacman -S --noconfirm --needed php php-fpm
-if [ "$?" != "0" ]; then /usr/bin/echo 'Failed: !!'; exit 4; fi
+e="$?"; [[ "$e" = "0" ]] || /usr/bin/echo 'Failed: !!' && exit "$e"
 
 ## PHP-FPM
 /usr/bin/cat <<'EOF' > /etc/nginx/php_fastcgi.conf
@@ -228,7 +228,7 @@ echo 'security.limit_extensions = .php .html .htm .shtml' >> /etc/php/php-fpm.d/
 
 ## PHP extras
 /usr/bin/pacman -S --noconfirm --needed pkg-config php-gd php-apcu nginx-mod-headers-more fcgiwrap php-imagick php-intl php-pspell
-if [ "$?" != "0" ]; then /usr/bin/echo 'Failed: !!'; exit 4; fi
+e="$?"; [[ "$e" = "0" ]] || /usr/bin/echo 'Failed: !!' && exit "$e"
 
 ## Services
 /usr/bin/systemctl enable nginx; wait
@@ -240,7 +240,7 @@ if [ "$?" != "0" ]; then /usr/bin/echo 'Failed: !!'; exit 4; fi
 
 # MySQL (viz MariaDB)
 /usr/bin/pacman -S --noconfirm --needed mariadb
-if [ "$?" != "0" ]; then /usr/bin/echo 'Failed: !!'; exit 4; fi
+e="$?"; [[ "$e" = "0" ]] || /usr/bin/echo 'Failed: !!' && exit "$e"
 /usr/bin/mysql_install_db --user=mysql --basedir=/usr --datadir=/var/lib/mysql
 ## Start it now so it works when we run the secure installation
 /usr/bin/systemctl enable mariadb; wait
@@ -271,7 +271,7 @@ EOF
 
 # Firewall
 /usr/bin/pacman -S --noconfirm --needed ufw
-if [ "$?" != "0" ]; then /usr/bin/echo 'Failed: !!'; exit 4; fi
+e="$?"; [[ "$e" = "0" ]] || /usr/bin/echo 'Failed: !!' && exit "$e"
 /usr/bin/systemctl enable ufw; wait
 /usr/bin/systemctl start ufw; wait
 /usr/bin/ufw allow 80/tcp
@@ -325,7 +325,7 @@ host = localhost" > /opt/verb/conf/mysqlboss.cnf
 
 # Monit
 /usr/bin/pacman -S --noconfirm --needed monit
-if [ "$?" != "0" ]; then /usr/bin/echo 'Failed: !!'; exit 4; fi
+e="$?"; [[ "$e" = "0" ]] || /usr/bin/echo 'Failed: !!' && exit "$e"
 ## Copy configs (These seem to have precedence, files in /etc/monit seem to conflict with them but may be u/usr/bin/sed instead
 /usr/bin/mkdir -p /etc/monit/monitrc.d
 sed -i "s?#  include /etc/monit.d?  include /etc/monit.d?" /etc/monitrc
@@ -342,23 +342,23 @@ sed -i "s?#  include /etc/monit.d?  include /etc/monit.d?" /etc/monitrc
 
 # Pre-install Go (may be redundand as Go is a dependency in make-preverber)
 /usr/bin/pacman -S --noconfirm --needed go
-if [ "$?" != "0" ]; then /usr/bin/echo 'Failed: !!'; exit 4; fi
+e="$?"; [[ "$e" = "0" ]] || /usr/bin/echo 'Failed: !!' && exit "$e"
 
 # Pre-install Postfix server packages
 /usr/bin/pacman -S --noconfirm --needed postfix postfix-mysql dovecot pigeonhole mailutils cyrus-sasl opendkim msmtp
-if [ "$?" != "0" ]; then /usr/bin/echo 'Failed: !!'; exit 4; fi
+e="$?"; [[ "$e" = "0" ]] || /usr/bin/echo 'Failed: !!' && exit "$e"
 
 # Pre-install inkCert-LE
 /usr/bin/pacman -S --noconfirm --needed certbot certbot-nginx
-if [ "$?" != "0" ]; then /usr/bin/echo 'Failed: !!'; exit 4; fi
+e="$?"; [[ "$e" = "0" ]] || /usr/bin/echo 'Failed: !!' && exit "$e"
 
 # Pre-install inkDNS
 /usr/bin/pacman -S --noconfirm --needed bind dnsutils certbot-dns-rfc2136
-if [ "$?" != "0" ]; then /usr/bin/echo 'Failed: !!'; exit 4; fi
+e="$?"; [[ "$e" = "0" ]] || /usr/bin/echo 'Failed: !!' && exit "$e"
 
 # Pre-install vsftpd
 /usr/bin/pacman -S --noconfirm --needed vsftpd
-if [ "$?" != "0" ]; then /usr/bin/echo 'Failed: !!'; exit 4; fi
+e="$?"; [[ "$e" = "0" ]] || /usr/bin/echo 'Failed: !!' && exit "$e"
 
 # Remove unneeded packages
 /usr/bin/pacman -Qdt --noconfirm
